version: '2'
services:
    postgres:
      image: postgres:alpine
      restart: always
      environment:
       - "POSTGRES_USER=keycloak"
       - "POSTGRES_PASSWORD=keycloak"
       - "POSTGRES_DB=keycloak"
      volumes:
       - "db-data:/var/lib/postgresql/data"
      networks:
       - keycloak
    keycloak:
      image: jboss/keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: keycloak
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        PROXY_ADDRESS_FORWARDING: 'true'
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it 
        #shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      #ports:
      #  - 8080:8080
      depends_on:
        - postgres
      networks:
       - keycloak
    adminer:
      image: adminer
      restart: always
      ports:
        - 9090:8080
      depends_on:
        - postgres
      networks:
       - keycloak
    nginx:
      image: nginx
      restart: always
      ports:
        - 443:443
      volumes:
        - ./nginx:/etc/nginx/conf.d
      depends_on:
        - keycloak
      networks:
        - keycloak


networks:
    keycloak:
      driver: bridge

volumes:
    db-data:
      driver: local
